### ISSUE TITLE
Comparison to alternatives

### ISSUE THREAD

**Issue by cocowalla** [dazinator/stint#5]
Hi, this looks interesting! I was wondering if you might add a brief comparison to the readme, to see how it differs to Quartz, Hangfire, FluentScheduler and Gofer.NET?

As Stint is new, if would be nice to see a basic roadmap too, so we can get an idea of the direction.

Thanks for another nice OSS project! 🙏

**Comment by dazinator** [comment]
Initial response until I get the time to work on this issue more. I can't speak much around contrasting at the moment, but here are a few goals for this library:

1. Focused on scheduled jobs only (hangfire calls them recurring jobs). Why? I think there are lots of other choices for fire and forget (delayed) one-time jobs.
2. No UI - not a concern for this library. 
3. Minimal infrastructure by default. Stint should work out of the box with your single application instance without forcing any dependencies such as sql server, redis etc etc. The only dependency it has by default is the file system, to save very simple anchor files.
4. Flexible and scalable. When you want to scale to multiple applications that may be running stint in a cluster - it should be simple for you to enable that. Right now this story looks like this:
    - When adding stint services, utilise the option to specify the file path where anchors should be stored - specify a file share. Alternatively register your own `IAnchorStore` and persist anchor's however you like - for example to a central database.
    - When adding stint services, add your own `ILockProvider`. This should return an IDisposable that represents a distributed lock. I don't provide any implementations beyond the default (which basically no-op's) however must scaled applications usually have their own IDistributed lock mechanism so `stint` allows you to plug your own here.
    - When configuring your stint scheduled jobs using the `IOptions` pattern, each node in the cluster should configure from a central source for example, an appsettings json file on a file share. Unless of course you want to `shard` scheduled jobs - i.e have some execute on node A, others execute on node B etc - in which case each node can configure using its own configuration source. Not much for `stint` to do here, as it outsources this concern to the .net core configuration system, or ore specifically, the `IOptions` mechanism. This also means that the scheduler can reload when configuration source changes are detected at runtime - for example the config file is edited.
5. Written from ground up for modern .net core / .net 5 stack. No `OWIN` packages, no legacy asp.net support etc (although you probably could get it to run under legacy asp.net)
6. Deployment Companion packages to allow your application to be installed as a Linux service or a Windows service very easily. Mac will eventually be added to the roadmap later. Although I may factor these companion packages out to another repo time. Why? Running a job scheduler behind IIS means that IIS can terminate the process based on app pool settings, and then start it again when the first request is received. Hangfire addresses this by admitting the limitation, and explaining some options - like changing the app pool settings to enable "Always on" -or running a windows service instead.  `Stint` will be subject to the same limitations when run behind IIS as Hangfire. However assuming you do want to deploy your application as a service, there is no super trivial way for a developer to create an application today that can be easily downloaded and installed as a service on windows or linux in a simple mannor. The install instructions are usually something like: On Windows you download the binaries, put them in this directory, then open and use an unrelated command line tool `svcutil` with the right paramters to install the application as  service. These steps look different on linux. `stint` will make it a little easier via a companion package - that extends your application entry point to include a command line. You can now download your application binaries to a linux or windows machine and execute this command line with your own binaries (so its the same step on windows and linux) to `install` your app as a windows service or a linux service on that machine. So it's basically a way to bundle the service install mechanism into your appllication's entry point in a cross platform mannor. The companion package for linux is already in this repo, i've not done windows yet.
7. Composite job triggers. `stint` scheduler builds an `IChangeToken` producer for each scheduled job, that returns composite `IChangeToken`s. The scheduler executes the job when the `IChangeToken` is signalled. Part of the composite change token, is the thing that signals based on the scheduled execution time for this job. However as I use `changify` library, its easy to include other things when building this composite, or to even filter out specific signals based on your own logic. So on the roadmap will be a way to take control of this aspect of building the change token producer, so you can have more flexibility over what might trigger the recurring job, so it doesn't just have to be it's cron schedule. For example you could:-
    - Include a manual trigger so that you can also get the job to execute when you invoke that trigger callback. 
    - Job chaining - execute a recurring job off the back of another job finishing.
    - Approval workflow - intercept when the scheduled job is signalled but don't pass the signal on - create some record somewhere that the job needs to be manually approved. Once the approver has approved, have your custom change token fire, and now the job will execute.

**Comment by cocowalla** [comment]
That's a pretty comprehensive response actually - thanks!

**Comment by dazinator** [comment]
No probs. I should also mention one other significant difference between Stint and hangfire. Hangfire sets up its own dedicated ThreadPool for worker threads to execute jobs on. Stint just uses the [default thread pool](https://docs.microsoft.com/en-us/dotnet/standard/threading/the-managed-thread-pool) to execute jobs on. If you are running Stint jobs in a seperate process to your actual application, then there is no issue either way (so no need for stint to have a dedicated thread pool that I can see). However if you are running stint within the same process as your application, for example lets say its an an asp.net core web application - you'll want to avoid having your jobs block thread pool threads for long periods of time - this way they are returned to the pool and available for application tasks such as serving new requests - which allows greater throughput particularly in high traffic web applications. Imho, not blocking threads for long periods is just good practice anyway - and it's why I remain comfortable not adding a seperate dedicated thread pool for stint. Stint has faith in developers implementing async jobs (IJob interface) that they will most likely be trying to avoid blocking threads for long periods by taking advantage of all the modern async based Api's that we have today.. and if they do insist on doing a Thread.Sleep for 3 hours, and it's detracting from their web app performance then the best solution for them would be to either refactor their job, or to run Stint jobs in a seperate / dedicated process I.e seperate from their web app.

**Comment by dazinator** [comment]
Update on this, as the scope has slightly increased with some new features I just merged.
- Jobs can now be configured with different trigger types. Scheduled trigger is one type. Another type of trigger is called `JobCompletion` trigger, which allows you to configure the job to run, when another job with a specific name completes. This allows job "chains" to be configured. You can add triggers of different types for the same job, the job will be triggered when any one of them signals. A thrid type of trigger is called `Manual` trigger. If the job has a manual trigger configured then you can use a service to invoke it's manual trigger using the job name as an argument - which would be the kind of thing you might do if you want to add a button to some UI to trigger the job yourself.
